fix about, contact, career
Ozoemenamsolomon/orthoex-store pull request #6
Opened 2022-12-06 11:50 UTC by ebuka-nwabueze

2022-12-09 21:10 UTC, Ozoemenamsolomon requested changes
Please look into these reviews and let us align on them later

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +						{event.event_format}
use camelCase for your attributes

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +						<span>2nd Aug 2022 - 7th Aug 2022</span>
extract the date, location, duration etc

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +						<p>{priceFormatter.format(10000)}</p>
nice!

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +						<p>{priceFormatter.format(10000)}</p>
but extract the price too

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +				{/* left content */}
remove this comment, comments won't be necessary if fuctions and variables are named properly

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +// import People
!

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +const StyledDetailsSection = styled.section`
use div, not section

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/styled/index.tsx
> +export const StyledCustomButton = styled.button<StyledButtonProps>`
What's this?

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +				{/* left content */}
All your styled components must not have styled prefix, they are redundant

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/ServiceStandard.tsx
> +						<ImageDescription length={servicesIcon.length} key={index}>
add a discriminator to the key

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEventCard.tsx
> +const StyledInfoSection = styled.section``;
use div [check out](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/styled/Forms.tsx
> +  @media(min-width: 768px){
remove

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEvents.tsx
> +	const onClickLoad = () => {
make your variable names more decriptive, this function should be called `loadMoreEvent`, I guess that's what it's doing

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEvents.tsx
> +		width: 16rem;
doesn't seem right 🤔

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/styles/globals.css
> +.swiper-pagination-bullet-active {
remove this and put it within the swiper wrapper

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/pages/contact.tsx
> +	type InputChangeType =
type def outside component

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/pages/contact.tsx
> +										type="text"
type="tel"

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/pages/contact.tsx
> +	const { fullname, email, message, phone } = formData;
camelCase

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/data/eventsData.ts
> +  event_format: string,
make this an enum type

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/data/eventsData.ts
> +  start_date: string,
`startDateTime` combine the date and time using ISO format, instead of having separate attribute for `startTime`

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/data/eventsData.ts
> +  start_date: string,
For example, "2007-04-05T14:30Z" or "2007-04-05T12:30−02:00".

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/data/eventsData.ts
> +  course_info: {
this should be of type string, a markdown string

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/data/openJobPositionsData.ts
> +	type: string;
of type enum

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/data/openJobPositionsData.ts
> +	applyLink: string;
you have to be consistent with your naming convention, here you are using camelCase which I find better but you're using another convention somewhere else

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/ServiceStandard.tsx
> +						<ImageDescription length={servicesIcon.length} key={index}>
use the ServiceCard here

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/ServiceStandard.tsx
> +		width: ${({ length }) => (length > 5 ? '33%' : '50%')};
doesn't seem right

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/pages/careers.tsx
> +			{/* Open positions */}
if you name your variables well you won't need comments

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/pages/careers.tsx
> +			<StyledHiringProcess>
this should be contained in the container above

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/shared/Address.tsx
> +const Address = () => {
why shared? when you're just using it on contact page?

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/shared/HeaderParagraph.tsx
> +const HeaderParagraph: React.FC<HeaderParagraphProps> = ({ data }) => {
shared?

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/JobPositonCard.tsx
> +export const StyledJobPositionCard = styled.div`
why are you exporting these?

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/JobPositonCard.tsx
> +export const StyledJobPositionCard = styled.div`
why? when you're just using it on this file?

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/JobPositonCard.tsx
> +	@media (min-width: 768px) {
remove

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/JobPositonCard.tsx
> +			<CTALink clasname="btn" href={data.applyLink}>
className

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/ImageInfoHeader.tsx
> +	width: 100%;
div is a block element

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEvents.tsx
> +	const [increment] = useState(1);
you don't need useState here, a simple variable will do

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/FeaturedEvents.tsx
> +	@media (min-width: 768px) {
remove

2022-12-09 21:10 UTC, Ozoemenamsolomon commented on src/components/SupportInfoCard.tsx
> +					<Link key={index} href={link} passHref>
discriminate

2022-12-18 00:14 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +						{event.event_format}
Done

2022-12-18 00:20 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +						<p>{priceFormatter.format(10000)}</p>
Done

2022-12-18 00:20 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +				{/* left content */}
Ok Noted.

2022-12-18 00:21 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +// import People
Resolved

2022-12-18 00:21 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +const StyledDetailsSection = styled.section`
Resolved

2022-12-18 00:26 UTC, ebuka-nwabueze commented on src/components/styled/index.tsx
> +export const StyledCustomButton = styled.button<StyledButtonProps>`
It was used for the initial design but has been replaced with CTA

2022-12-18 01:05 UTC, ebuka-nwabueze commented on src/components/ServiceStandard.tsx
> +						<ImageDescription length={servicesIcon.length} key={index}>
Resolved

2022-12-18 01:07 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +const StyledInfoSection = styled.section``;
Resolved

2022-12-18 01:08 UTC, ebuka-nwabueze commented on src/components/styled/Forms.tsx
> +  @media(min-width: 768px){
Resolved

2022-12-18 01:08 UTC, ebuka-nwabueze commented on src/components/FeaturedEvents.tsx
> +	const onClickLoad = () => {
Resolved.

2022-12-18 01:17 UTC, ebuka-nwabueze commented on src/components/FeaturedEvents.tsx
> +		width: 16rem;
Changed the targeting to a class.

2022-12-18 01:20 UTC, ebuka-nwabueze commented on src/styles/globals.css
> +.swiper-pagination-bullet-active {
According to the documentation. The css resides in the global style sheet

2022-12-18 01:22 UTC, ebuka-nwabueze commented on src/pages/contact.tsx
> +	type InputChangeType =
Resolved

2022-12-18 01:23 UTC, ebuka-nwabueze commented on src/pages/contact.tsx
> +	const { fullname, email, message, phone } = formData;
resolved

2022-12-18 01:24 UTC, ebuka-nwabueze commented on src/pages/contact.tsx
> +										type="text"
resolved

2022-12-18 01:28 UTC, ebuka-nwabueze commented on src/data/eventsData.ts
> +  start_date: string,
Resolved

2022-12-18 01:29 UTC, ebuka-nwabueze commented on src/data/eventsData.ts
> +  event_format: string,
I don't understand what you mean. 
Which of the property should be enum?
They are all different id, title and eventFormat

2022-12-18 01:31 UTC, ebuka-nwabueze commented on src/data/openJobPositionsData.ts
> +	type: string;
Same as the earlier comment. Not sure what you mean by enum here?

2022-12-18 01:33 UTC, ebuka-nwabueze commented on src/data/eventsData.ts
> +  course_info: {
Not sure what you mean here?

2022-12-18 01:33 UTC, ebuka-nwabueze commented on src/data/openJobPositionsData.ts
> +	applyLink: string;
All properties are now camelCase

2022-12-18 01:34 UTC, ebuka-nwabueze commented on src/components/ServiceStandard.tsx
> +		width: ${({ length }) => (length > 5 ? '33%' : '50%')};
resolved

2022-12-18 01:40 UTC, ebuka-nwabueze commented on src/pages/careers.tsx
> +			<StyledHiringProcess>
It is not meant to be within the container. The containter has padding and it doesn't match with the design

2022-12-18 01:40 UTC, ebuka-nwabueze commented on src/components/shared/Address.tsx
> +const Address = () => {
I did it as it can be reusable

2022-12-18 01:42 UTC, ebuka-nwabueze commented on src/components/shared/HeaderParagraph.tsx
> +const HeaderParagraph: React.FC<HeaderParagraphProps> = ({ data }) => {
I created the folder to hold components that can be used in multiple places. The project is growing and folder structure is expanding.

2022-12-18 01:43 UTC, ebuka-nwabueze commented on src/components/JobPositonCard.tsx
> +export const StyledJobPositionCard = styled.div`
Resolved

2022-12-18 01:43 UTC, ebuka-nwabueze commented on src/components/JobPositonCard.tsx
> +			<CTALink clasname="btn" href={data.applyLink}>
resolved

2022-12-18 01:45 UTC, ebuka-nwabueze commented on src/components/ImageInfoHeader.tsx
> +	width: 100%;
resolved

2022-12-18 01:45 UTC, ebuka-nwabueze commented on src/components/FeaturedEvents.tsx
> +	@media (min-width: 768px) {
resolved

2022-12-18 01:46 UTC, ebuka-nwabueze commented on src/components/SupportInfoCard.tsx
> +					<Link key={index} href={link} passHref>
resolved

2022-12-18 01:49 UTC, ebuka-nwabueze commented on src/components/FeaturedEvents.tsx
> +	const [increment] = useState(1);
resolved

2022-12-18 01:49 UTC, ebuka-nwabueze commented on src/components/JobPositonCard.tsx
> +	@media (min-width: 768px) {
resolved

2022-12-18 01:50 UTC, ebuka-nwabueze commented on src/components/FeaturedEventCard.tsx
> +						<span>2nd Aug 2022 - 7th Aug 2022</span>
I will create a function for this.

2022-12-18 18:27 UTC, Ozoemenamsolomon approved these changes
looks good

2022-12-18 18:29 UTC, merged